development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: alonetone_test2
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: 
  username: alonetone_prod
  password: 
  host: localhost
  encoding: utf8

